export const TASK_HISTORY_ACTIONS = {
  CREATED: 'TASK_CREATED',
  UPDATED: 'TASK_UPDATED',
  STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  DELETED: 'TASK_DELETED',
  ASSIGNED: 'TASK_ASSIGNED',
  UNASSIGNED: 'TASK_UNASSIGNED',
} as const;

export const TASK_ACTIVITY_ACTIONS = {
  CREATED: 'TASK_CREATED',
  UPDATED: 'TASK_UPDATED',
  DELETED: 'TASK_DELETED',
  ASSIGNED: 'TASK_ASSIGNED',
  UNASSIGNED: 'TASK_UNASSIGNED',
  STATUS_CREATED: 'TASK_STATUS_CREATED',
  STATUS_UPDATED: 'TASK_STATUS_UPDATED',
  STATUS_DELETED: 'TASK_STATUS_DELETED',
} as const;
