export const TASK_HISTORY_ACTIONS = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  DELETED: 'DELETED',
  ASSIGNED: 'ASSIGNED',
  UNASSIGNED: 'UNASSIGNED',
  COMMENTED: 'COMMENTED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',
  COMMENT_DELETED: 'COMMENT_DELETED',
} as const;

export const TASK_ACTIVITY_ACTIONS = {
  CREATED: 'TASK_CREATED',
  UPDATED: 'TASK_UPDATED',
  DELETED: 'TASK_DELETED',
  ASSIGNED: 'TASK_ASSIGNED',
  UNASSIGNED: 'TASK_UNASSIGNED',
  STATUS_CREATED: 'TASK_STATUS_CREATED',
  STATUS_UPDATED: 'TASK_STATUS_UPDATED',
  STATUS_DELETED: 'TASK_STATUS_DELETED',
} as const;
